version : '3,7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432.5432'
    enviroment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=fbrpass
      - POSTGRES_DB=fbr

    volumes:
      - fbr_pg_Data:bitnami/postgresql

volumes:
  fbr_pg_Data:bitnami/postgresql:
