// CADASTRAR administrador 
POST http://localhost:3000/administrador/cadastro
Content-Type: application/json

{
    "nome":"William",
    "cpf":"000.000.000-00",
    "sexo":"m",
    "email":"carlosmaycon443@gmail.com",
    "senha":"1234",
    "cnpj":""
}

### LOGAR administrador
POST http://localhost:3000/administrador/login
Content-Type: application/json

{
"email":"carlosmaycon443@gmail.com",
"senha":"1234"
}
