// CADASTRAR CLIENTE 
POST http://localhost:3000/cliente/cadastro
Content-Type: application/json

{
    "nome":"William",
    "cpf":"00000000000",
    "sexo":"m",
    "email":"carlosmaycon443@gmail.com",
    "telefone":"(81) 9 9999-9999",
    "senha":"1234",
    "cnpj":""
}

### LOGAR CLIENTE
POST http://localhost:3000/cliente/login
Content-Type: application/json

{
"email":"carlosmaycon443@gmail.com",
"senha":"1234"
}

### PUXAR TODOS OS CLIENTES
GET http://localhost:3000/cliente
Content-Type: application/json

{

}

### PUXAR UM CLIENTE POR ID 
GET http://localhost:3000/cliente/2
Content-Type: application/json

{

}