//CADASTRAR PROVEDOR
POST http://localhost:3000/provedor/cadastro
Content-Type: application/json

{
    "nome":"Breno",
    "cpf":"none",
    "sexo": "m",
    "email": "brenoluisadv@gmail.com",
    "senha": "123",
    "cnpj": ""
    //Adicionar ser possivel apenas com token de adm
}

###
//LOGAR PROVEDOR
POST http://localhost:3000/provedor/login
Content-Type: application/json

{

}