//CADASTRAR PROVEDOR
POST http://localhost:3000/provedor/cadastro
Content-Type: application/json

{
    "nome":"William",
    "cpf":"none",
    "sexo": "m",
        "email": "carlosmaycon443@gmail.com",
        "senha": "123",
        "cnpj": ""
}

###