//CADASTRAR SERVIÇO
POST http://localhost:3000/servico/criar
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhcmxvc21heWNvbjQ0M0BnbWFpbC5jb20iLCJzZW5oYSI6IjEyMzQiLCJydWxlIjoiYWRtaW5pc3RyYWRvciIsImlhdCI6MTczMTg0NzE5MywiZXhwIjoxNzMxODU0MzkzfQ.xmAl6azI5rd6Z6Or7lhu2ynTghEnBmOGGSNaDF3WH9s

{
    "nome":"instalação de ponto de rede",
    "descricao":"a instalação de um ponto que interliga varias casas"
}

### 
//Atribuir serviço a um provedor
POST http://localhost:3000/servico/definir
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhcmxvc21heWNvbjQ0M0BnbWFpbC5jb20iLCJzZW5oYSI6IjEyMzQiLCJydWxlIjoiYWRtaW5pc3RyYWRvciIsImlhdCI6MTczMTg0NzQ1NCwiZXhwIjoxNzMxODU0NjU0fQ.1BDUs6MCNO2WbpWw5aPVwxdGoVVEGClbflkffSaiPzU

{
    "servicoId": 3,
    "provedorId": [3]
    //ADICIONAR HASH DE ADM
}

### 
//Ver todos os serviços cadastrados
GET http://localhost:3000/servico/get
//Sempre trocar pelo novo token de adm
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhcmxvc21heWNvbjQ0M0BnbWFpbC5jb20iLCJzZW5oYSI6IjEyMzQiLCJydWxlIjoiYWRtaW5pc3RyYWRvciIsImlhdCI6MTczMDk0OTE1MSwiZXhwIjoxNzMwOTU2MzUxfQ.7ww01AHpiozc4zlJKtzRM_DJRN5eJuy_g8mtD8lusbk
Content-Type: application/json

### 

PUT http://localhost:3000/servico/editar
Content-Type: application/json

{
    "nome": "editou",
    "descricao": "req.body.descricao",
    "servicoId": "2"
}

###